server:
  port: 9999
#  servlet:
# 应用访问名称，小写
#    context-path: /demo

spring:
  datasource:
    sqlite:
      url: jdbc:sqlite:./data.sqlite

  web:
    resources:
      static-locations:
#debug: true
