server:
  port: 9999
#  servlet:
# 应用访问名称，小写
#    context-path: /demo

spring:
  datasource:
    sqlite:
      url: jdbc:sqlite:./data.sqlite
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none


  web:
    resources:
      static-locations:
#debug: true
